# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord_o',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('coord_ox', models.CommaSeparatedIntegerField(max_length=200)),
                ('coord_oy', models.CommaSeparatedIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coord_x',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('coord_xx', models.CommaSeparatedIntegerField(max_length=200)),
                ('coord_xy', models.CommaSeparatedIntegerField(max_length=200)),
            ],
        ),
    ]
