# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-25 11:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180904_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty_level',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='coord_o',
            name='coord_ox',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='coord_o',
            name='coord_oy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='coord_x',
            name='coord_xx',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='coord_x',
            name='coord_xy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
