# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-01 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181025_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='difficulty_level',
            old_name='level',
            new_name='level_in_model',
        ),
    ]
